---
- name: "Updating Packages"
  become: yes
  apt:
    update_cache: yes

- name: "Upgrading Packages"
  become: yes
  apt:
    upgrade: yes

- name: "Installing Dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: "Copying Backend Folder"
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm install
- name: "Building Backend Service"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod
- name: "Running Backend Service with PM2"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --no-automation --name "backend" -- run start
    pm2 ls